<?php
declare(strict_types=1);

namespace Itools\SvgValidator\Tests\Unit;

use Itools\SvgValidator\SvgValidator;
use Itools\SvgValidator\Tests\Support\SvgValidatorTestCase;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * CSS in <style> elements and style= attributes: the banned tokens, url(), the
 * embedded-font carve-out, comments, CDATA, and text from child elements.
 *
 * Code: css-not-allowed. The same rule runs on both places, so the token
 * providers feed one test for the element and one for the attribute.
 */
class CssTest extends SvgValidatorTestCase
{
    //region Accepted CSS

    #[DataProvider('acceptedCssProvider')]
    public function testAcceptedInStyleElement(string $css): void
    {
        $this->assertAccepts($this->svg("<style>$css</style>"));
    }

    #[DataProvider('acceptedCssProvider')]
    public function testAcceptedInStyleAttribute(string $css): void
    {
        $this->assertAccepts($this->svg('<rect style="' . htmlspecialchars($css, ENT_QUOTES) . '"/>'));
    }

    public static function acceptedCssProvider(): array
    {
        return [
            'empty'                    => [''],
            'plain rules'              => ['.st0{fill:#1D4ED8;stroke:none} .st1{font-family:\'Helvetica Neue\', Arial, sans-serif}'],
            'fragment url'             => ['.a{fill:url(#grad)}'],
            'fragment url, quoted'     => ['.a{fill:url(\'#grad\');filter:url( "#f" )}'],
            'keyframes'                => ['@keyframes spin{from{transform:rotate(0)}to{transform:rotate(360deg)}} .a{animation:spin 1s linear infinite}'],
            'media query'              => ['@media (prefers-color-scheme: dark){.a{fill:#fff}}'],
            'font-face with ttf'       => ['@font-face{font-family:F;src:url(data:font/ttf;base64,AAAA) format("truetype")}'],
            'font-face with woff2'     => ['@font-face{font-family:F;src:url("data:font/woff2;base64,AAAA")}'],
            'font-face, no mime type'  => ['@font-face{font-family:F;src:url(data:;base64,AAAA)}'],
            'font data outside font-face' => ['.a{fill:url(data:font/ttf;base64,AAAA)}'],   // the carve-out applies anywhere: there is no tokenizer to find the block, and a font in fill loads nothing
            'comment'                  => ['/* Generated by a design tool */ .a{fill:red}'],
            'string with a colon'      => ['.a::before{content:"https://example.com"}'],
        ];
    }

    #[DataProvider('styleElementShapeProvider')]
    public function testStyleElementShapes(string $body): void
    {
        $this->assertAccepts($this->svg($body));
    }

    public static function styleElementShapeProvider(): array
    {
        return [
            'empty element'     => ['<style/>'],
            'empty pair'        => ['<style></style>'],
            'with type'         => ['<style type="text/css">.a{fill:red}</style>'],
            'cdata wrapped'     => ['<style><![CDATA[ .a{fill:red} ]]></style>'],
            'inside defs'       => ['<defs><style>.a{fill:red}</style></defs>'],
            'two style elements' => ['<style>.a{fill:red}</style><rect/><style>.b{fill:blue}</style>'],
        ];
    }

    //endregion
    //region Banned Tokens

    #[DataProvider('bannedCssProvider')]
    public function testBannedInStyleElement(string $css, string $detail): void
    {
        $this->assertRejects($this->svg("<style>$css</style>"), 'css-not-allowed', $detail);
    }

    #[DataProvider('bannedCssProvider')]
    public function testBannedInStyleAttribute(string $css, string $detail): void
    {
        $this->assertRejects($this->svg('<rect style="' . htmlspecialchars($css, ENT_QUOTES) . '"/>'), 'css-not-allowed', $detail);
    }

    public static function bannedCssProvider(): array
    {
        return [
            '@import'                   => ['@import url("https://evil.example/x.css");', '@import'],
            '@import, upper case'       => ['@IMPORT "x.css";', '@IMPORT'],
            '@charset'                  => ['@charset "UTF-8";', '@charset'],
            'backslash escape'          => ['.a{fill:red\;}', '\\'],
            'image()'                   => ['.a{background:image(x.png)}', 'image('],
            'image-set()'               => ['.a{background:image-set("x.png" 1x)}', 'image-set('],
            'src()'                     => ['.a{background:src("x.png")}', 'src('],
            'expression()'              => ['.a{width:expression(alert(1))}', 'expression('],
            '-moz-binding'              => ['.a{-moz-binding:url(#x)}', '-moz-binding'],
            'behavior'                  => ['.a{behavior:url(#x)}', 'behavior:'],
            'behavior with space'       => ['.a{behavior : url(#x)}', 'behavior :'],
            'external url'              => ['svg{background-image:url(https://evil.example/x.png)}', 'url(https://evil.example/x.png'],
            'external url, quoted'      => ['svg{background-image:url("https://evil.example/x.png")}', 'url("https://evil.example/x.png"'],
            'relative url'              => ['.a{fill:url(p.svg#a)}', 'url(p.svg#a'],
            'protocol-relative url'     => ['.a{fill:url(//evil.example/p.svg#a)}', 'url(//evil.example/p.svg#a'],
            'javascript url'            => ['.a{fill:url(javascript:alert(1))}', 'url(javascript:alert(1'],
            'data image in css'         => ['.a{background:url(data:image/png;base64,AAAA)}', 'url(data:image/png;base64,AAAA'],
        ];
    }

    //endregion
    //region Where the Text Comes From

    /** Comment contents are scanned too: a string like content:"/*" can fake a comment start, so stripping them is unsafe. */
    public function testCommentsAreScanned(): void
    {
        $this->assertRejects($this->svg('<style>/* @import "x.css"; */ .a{fill:red}</style>'), 'css-not-allowed', '@import');
    }

    /** Strings are scanned too, so a CSS string containing a banned token is rejected. Over-rejecting is the safe side. */
    public function testStringsAreScanned(): void
    {
        $this->assertRejects($this->svg('<style>.a::before{content:"@import"}</style>'), 'css-not-allowed', '@import');
    }

    public function testCdataIsScanned(): void
    {
        $this->assertRejects($this->svg('<style><![CDATA[ @import url("x.css"); ]]></style>'), 'css-not-allowed', '@import');
    }

    /** Browsers use the element's whole text content, child elements included. */
    public function testChildElementTextIsScanned(): void
    {
        $this->assertRejects($this->svg('<style>.a{fill:red}<title>@import "x.css";</title></style>'), 'css-not-allowed', '@import');
    }

    public function testEachStyleElementIsCheckedOnItsOwn(): void
    {
        $result = SvgValidator::checkString($this->svg('<style>.a{fill:red}</style><style>@import "x.css";</style><style>.b{fill:blue}</style>'));
        $this->assertSame(['css-not-allowed'], array_column($result->errors, 'code'));
    }

    /**
     * CDATA holding markup is plain text to a browser, and this library never re-serializes
     * a file, so the markup stays text. Sanitizers that rewrite CDATA into a text node have
     * had breakouts here (CVE-2022-23638); a validator has nothing to break out of.
     */
    public function testMarkupInsideCdataStaysText(): void
    {
        $markup = '<![CDATA[<p/><img src=x onerror=alert(1)>]]>';
        $this->assertAccepts($this->svg("<title>$markup</title>"));
        $this->assertAccepts($this->svg("<style>$markup</style>"));
    }

    //endregion
}
